version: '3.9'

services:
  node01:
    build: .
    container_name: node01
    hostname: node01
    volumes:
      - ./shared/node01/namenode:/opt/hadoop/yarn_data/hdfs/namenode
      - ./shared/conf/hadoop:/opt/hadoop/etc/hadoop
      - ./shared/node01/zookeeper:/opt/zookeeper/data
    networks:
      - hadoop-net
    ports:
      - "9870:9870"   # HDFS NameNode UI
      - "8088:8088"   # YARN ResourceManager UI


  node02:
    build: .
    container_name: node02
    hostname: node02
    volumes:
      - ./shared/node02/namenode:/opt/hadoop/yarn_data/hdfs/namenode
      - ./shared/conf/hadoop:/opt/hadoop/etc/hadoop
      - ./shared/node02/zookeeper:/opt/zookeeper/data
      - ./shared/node02/journalnode:/opt/hadoop/journal
    networks:
      - hadoop-net
    ports:
      - "9871:9870"   # HDFS NameNode UI
      - "8089:8088"   # YARN ResourceManager UI



  node03:
    build: .
    container_name: node03
    hostname: node03
    volumes:
      - ./shared/node03/datanode:/opt/hadoop/yarn_data/hdfs/datanode
      - ./shared/conf/hadoop:/opt/hadoop/etc/hadoop
      - ./shared/node03/zookeeper:/opt/zookeeper/data
    networks:
      - hadoop-net
    ports:
      - "9864:9864"   # HDFS Datanode UI
      - "8042:8042"   # NodeManager UI



  node04:
    build: .
    container_name: node04
    hostname: node04
    volumes:
      - ./shared/node04/datanode:/opt/hadoop/yarn_data/hdfs/datanode
      - ./shared/conf/hadoop:/opt/hadoop/etc/hadoop
      - ./shared/node04/journalnode:/opt/hadoop/journal
    networks:
      - hadoop-net
    ports:
      - "9865:9864"   # HDFS Datanode UI
      - "8043:8042"   # NodeManager UI



  node05:
    build: .
    container_name: node05
    hostname: node05
    volumes:
      - ./shared/node05/datanode:/opt/hadoop/yarn_data/hdfs/datanode
      - ./shared/conf/hadoop:/opt/hadoop/etc/hadoop
      - ./shared/node05/journalnode:/opt/hadoop/journal
    networks:
      - hadoop-net
    ports:
      - "9866:9864"   # HDFS Datanode UI
      - "8044:8042"   # NodeManager UI


networks:
  hadoop-net:
    driver: bridge
